#
# Converse configuration
#

# Where should players appeal their bans?
banurl: https://unraveledmc.com/appeal

# What mode is the server in?
mode: default

# What commands should be blocked when a player is muted?
muted_commands:
  - msg
  - reply
  - tell
  - me
  - mail

# Permissions configuration
permissions:
  op: default
  mod: mod
  admin: admin
  developer: developer
  executive: executive
  architect: architect

# Tab list configuration
tablist:
  # What should the header be?
  header:
    - "&c&oUnraveled"
    - "&8--+--"

  # What should the footer be?
  footer:
    - "&8--+--"
    - "&6&o/vote &7&oor die."
    - "&7unraveledmc.com"
    - "&7discord.gg/Wab3tFq"

# Game physics settings
config:
  item_drops: false
  fluid_place: false
  fire_place: false
  secret: false